// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8LeuMgxoplTTvZHLogXIMrBaOISp49nc',
    appId: '1:718196325364:web:47a14682313173f587d7a1',
    messagingSenderId: '718196325364',
    projectId: 'woc-seekr-ai',
    authDomain: 'woc-seekr-ai.firebaseapp.com',
    storageBucket: 'woc-seekr-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZQuqgt8Ey8sn_2Iel_k2gjTLbUzyfSv8',
    appId: '1:718196325364:android:f2b600779c0aec3587d7a1',
    messagingSenderId: '718196325364',
    projectId: 'woc-seekr-ai',
    storageBucket: 'woc-seekr-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8grEe3V1Cuyx1NHeiSoRcMQOSstzAv7Y',
    appId: '1:718196325364:ios:b86f64d43561b47087d7a1',
    messagingSenderId: '718196325364',
    projectId: 'woc-seekr-ai',
    storageBucket: 'woc-seekr-ai.firebasestorage.app',
    iosBundleId: 'com.example.seekrAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8grEe3V1Cuyx1NHeiSoRcMQOSstzAv7Y',
    appId: '1:718196325364:ios:b86f64d43561b47087d7a1',
    messagingSenderId: '718196325364',
    projectId: 'woc-seekr-ai',
    storageBucket: 'woc-seekr-ai.firebasestorage.app',
    iosBundleId: 'com.example.seekrAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8LeuMgxoplTTvZHLogXIMrBaOISp49nc',
    appId: '1:718196325364:web:9879c0e8413c940487d7a1',
    messagingSenderId: '718196325364',
    projectId: 'woc-seekr-ai',
    authDomain: 'woc-seekr-ai.firebaseapp.com',
    storageBucket: 'woc-seekr-ai.firebasestorage.app',
  );

}